"""
Generated by Claude Sonnet 5 on High effort setting

dynsys.py
=========

A framework for building and composing dynamical systems, with
numerics in JAX and composition topology described by a graph-tool
directed graph.

Design in a nutshell
--------------------
A `DynamicalSystem` has:
  - a named/sized **state** vector            x
  - a named/sized, optional **input** vector   u   (external or wired-in)
  - a JAX pytree of **parameters**             p
  - a **domain**: 'continuous' (dx/dt = f(x,u,p,t)) or 'discrete' (x_{k+1} = f(x,u,p,k))
  - a subset of its state variables flagged as **outputs** -- these are what
    other systems are allowed to read when you wire things together.

Two composition operations, both implemented as a *single* mechanism
(`CompositeSystem`, built from a graph-tool `Graph`):

  - `merge(*systems)`      -> block-diagonal composition: stack every state/
                              input/param, no coupling at all. Each subsystem
                              keeps evolving under its own independent dynamics.
  - `connect(systems, edges)` -> wire named outputs of some systems to named
                              inputs of others, described by a directed
                              graph-tool graph. This *is* "concatenation":
                              unconnected inputs remain free (composite's own
                              inputs); connected ones are driven by the source
                              system's current state.

`merge` is literally `connect` with an empty edge set, so both are the same
code path with different graphs.

Important consequence of "outputs are always a subset of state"
-----------------------------------------------------------------
There is no direct/instantaneous feedthrough term (an output can't be an
algebraic function of the input, only of the state). That means composing
systems -- even with feedback loops / cycles in the graph -- never creates an
algebraic loop: every system's output at time t is just a read of its own
state at time t, so evaluation order across subsystems doesn't matter
(a "Jacobi-style" / synchronous update). This is what lets `connect()` accept
cyclic graphs with no special handling.

Wiring granularity
------------------
Connections are made between whole *named* variables (e.g. "osc.pos" ->
"ctrl.err"), not individual vector elements. Sizes must match exactly. An
input variable may receive at most one incoming edge (no summing junctions);
an output variable may fan out to any number of destinations.

Mixed continuous/discrete composites
-------------------------------------
If you compose systems of different `domain`s, the resulting composite has
`domain == "hybrid"`. This framework only assembles the composed dynamics
function -- it does not integrate anything -- so simulating a hybrid system
(e.g. some subsystems stepped by an ODE solver, others by direct
substitution) is left to you, using each subsystem's `.domain` to dispatch.

Important note: being callable objects both classes are directly jittable
and behaves expectedly :)
"""

from __future__ import annotations

import warnings
from typing import Any, Callable, Dict, List, Literal, Optional, Sequence, Tuple, Union

import numpy as np
import jax.numpy as jnp
import graph_tool.all as gt

Domain = Literal["continuous", "discrete", "hybrid"]
Edge = Tuple[str, str, str, str]  # (src_system, src_output_var, dst_system, dst_input_var)


# --------------------------------------------------------------------------
# Variable specs / layout helpers
# --------------------------------------------------------------------------

class VarSpec:
    """A named, sized block of a state or input vector."""

    __slots__ = ("name", "size")

    def __init__(self, name: str, size: int = 1):
        if size < 1:
            raise ValueError(f"VarSpec '{name}' must have size >= 1, got {size}")
        self.name = name
        self.size = size

    def __repr__(self) -> str:
        return f"VarSpec({self.name!r}, size={self.size})"


def _layout(vars_: Sequence[VarSpec]) -> Tuple[Dict[str, Tuple[int, int]], int]:
    """name -> (start, end) slice within the concatenated vector, plus total size."""
    slices: Dict[str, Tuple[int, int]] = {}
    offset = 0
    for v in vars_:
        slices[v.name] = (offset, offset + v.size)
        offset += v.size
    return slices, offset

# --------------------------------------------------------------------------
# Recursive unpacking / time wiring helpers
# --------------------------------------------------------------------------

def _unpack(sys: DynamicalSystem) -> Tuple[List[DynamicalSystem], List[Edge]]:
    """A CompositeSystem -> (its immediate children, its edges as tuples).
    An atomic DynamicalSystem -> ([itself], [])."""
    if isinstance(sys, CompositeSystem):
        vprop = sys.graph.vertex_properties["system_name"]
        eprop = sys.graph.edge_properties["mapping"]
        edges: List[Edge] = []
        for e in sys.graph.edges():
            src_var, dst_var = eprop[e]
            edges.append((vprop[e.source()], src_var, vprop[e.target()], dst_var))
        return list(sys.subsystems), edges
    return [sys], []


def _wire_clock_recursive(sys: DynamicalSystem, target_names: set, input_name: str
                           ) -> Tuple[DynamicalSystem, List[str], set]:
    """Returns (possibly-rebuilt system, [dotted input names newly exposed by
    autonomizing, relative to `sys`], {target names matched inside `sys`}).
    A matched node -- leaf OR composite -- is autonomized as a whole (via the
    base, flattening `DynamicalSystem.autonomize(input_name)` -- called
    explicitly on the base class so a matched *composite* node still gets
    flattened rather than hitting CompositeSystem's own, differently-shaped
    `autonomize` override) and NOT recursed into further: overriding its own
    `t` already redirects every descendant, since a composite forwards one
    shared `t` to all its children."""
    if sys.name in target_names:
        return DynamicalSystem.autonomize(sys, input_name), [input_name], {sys.name}
    if not isinstance(sys, CompositeSystem):
        return sys, [], set()

    children, edges = _unpack(sys)
    new_children, bubbled, matched, changed = [], [], set(), False
    for child in children:
        new_child, child_bubbled, child_matched = _wire_clock_recursive(child, target_names, input_name)
        if child_bubbled:
            changed = True
            bubbled.extend(f"{child.name}.{e}" for e in child_bubbled)
        matched |= child_matched
        new_children.append(new_child)

    if not changed:
        return sys, [], matched
    return connect(new_children, edges, name=sys.name), bubbled, matched


def _promote_params_recursive(sys: DynamicalSystem, target_map: Dict[str, Optional[Sequence[str]]],
                                        state_prefix: str) -> Tuple[DynamicalSystem, set]:
    """Same recursive-match pattern as `_promote_params_recursive`, but
    promoting to STATE (trivial dynamics) rather than to input."""
    if sys.name in target_map:
        return DynamicalSystem.promote_params(sys, target_map[sys.name], state_prefix), {sys.name}
    if not isinstance(sys, CompositeSystem):
        return sys, set()
 
    children, edges = _unpack(sys)
    new_children, matched, changed = [], set(), False
    for child in children:
        new_child, child_matched = _promote_params_recursive(child, target_map, state_prefix)
        if child_matched:
            changed = True
        matched |= child_matched
        new_children.append(new_child)
 
    if not changed:
        return sys, matched
    return connect(new_children, edges, name=sys.name), matched


# --------------------------------------------------------------------------
# DynamicalSystem
# --------------------------------------------------------------------------

class DynamicalSystem:
    """
    A single dynamical system.

    Parameters
    ----------
    name : unique identifier (used when composing systems together)
    state_vars : ordered named/sized blocks making up the state vector x
    fn : f(x, u, p, t) -> dx_or_xnext, same shape as x.
         `u` is always provided (shape (0,) if input_vars is empty).
    input_vars : ordered named/sized blocks making up the (optional) input vector u
    outputs : subset of state_vars' *names* exposed to other systems when composing
    params : a JAX pytree of default parameters (e.g. a dict of jnp arrays)
    domain : 'continuous' (dx/dt = f(...)) or 'discrete' (x_next = f(...))
    """

    def __init__(
        self,
        name: str,
        state_vars: Sequence[VarSpec],
        fn: Callable[[jnp.ndarray, jnp.ndarray, Any, Any], jnp.ndarray],
        input_vars: Sequence[VarSpec] = (),
        outputs: Sequence[str] = (),
        params: Any = None,
        domain: Domain = "continuous",
    ):
        state_vars = tuple(state_vars)
        input_vars = tuple(input_vars)
        outputs = tuple(outputs)

        state_names = {v.name for v in state_vars}
        if len(state_names) != len(state_vars):
            raise ValueError(f"[{name}] duplicate state variable names")
        input_names = {v.name for v in input_vars}
        if len(input_names) != len(input_vars):
            raise ValueError(f"[{name}] duplicate input variable names")
        for o in outputs:
            if o not in state_names:
                raise ValueError(
                    f"[{name}] output '{o}' must be one of this system's state_vars "
                    f"{sorted(state_names)} (outputs are always a subset of the state)"
                )
        if domain not in ("continuous", "discrete", "hybrid"):
            raise ValueError("domain must be 'continuous', 'discrete', or 'hybrid'")

        if not isinstance(params, dict):
            raise TypeError(
                f"DynamicalSystems requires a dict of params, "
                f"got {type(params).__name__}"
            )

        self.name = name
        self.state_vars = state_vars
        self.input_vars = input_vars
        self.outputs = outputs
        self.fn = fn
        self.default_params = params
        self.domain = domain

        self._state_by_name = {v.name: v for v in state_vars}
        self._input_by_name = {v.name: v for v in input_vars}
        self._state_slices, self.state_size = _layout(state_vars)
        self._input_slices, self.input_size = _layout(input_vars)

    # -- introspection -----------------------------------------------------

    def has_input(self, name: str) -> bool:
        return name in self._input_slices

    def has_output_var(self, name: str) -> bool:
        return name in self.outputs

    def state_slice(self, name: str) -> Tuple[int, int]:
        return self._state_slices[name]

    def input_slice(self, name: str) -> Tuple[int, int]:
        return self._input_slices[name]

    @property
    def output_indices(self) -> np.ndarray:
        """Indices into the state vector corresponding to (in order) `self.outputs`."""
        idxs: List[int] = []
        for o in self.outputs:
            a, b = self._state_slices[o]
            idxs.extend(range(a, b))
        return np.asarray(idxs, dtype=np.int32)

    @property
    def output_size(self) -> int:
        return int(self.output_indices.size)

    def get_output(self, x: jnp.ndarray) -> jnp.ndarray:
        if not self.outputs:
            return jnp.zeros((0,), dtype=x.dtype)
        return x[self.output_indices]

    def split_state(self, x: jnp.ndarray) -> Dict[str, jnp.ndarray]:
        return {name: x[a:b] for name, (a, b) in self._state_slices.items()}

    def split_input(self, u: jnp.ndarray) -> Dict[str, jnp.ndarray]:
        return {name: u[a:b] for name, (a, b) in self._input_slices.items()}

    def pack_state(self, d: Dict[str, Any]) -> jnp.ndarray:
        return jnp.concatenate([jnp.atleast_1d(jnp.asarray(d[v.name])) for v in self.state_vars])

    def pack_input(self, d: Dict[str, Any]) -> jnp.ndarray:
        if not self.input_vars:
            return jnp.zeros((0,))
        return jnp.concatenate([jnp.atleast_1d(jnp.asarray(d[v.name])) for v in self.input_vars])

    # -- evaluation ----------------------------------------------------------

    def __call__(self, x: jnp.ndarray, u: Optional[jnp.ndarray] = None,
                 p: Any = None, t: Any = 0.0) -> jnp.ndarray:
        if u is None:
            u = jnp.zeros((self.input_size,))
        if p is None:
            p = self.default_params
        return self.fn(x, u, p, t)

    # -- time handling ---------------------------------------------------------
 
    def autonomize(self, input_name: str = "t_in") -> "DynamicalSystem":
        """
        Expose this system's time dependence as an ordinary, wireable input
        variable instead of the implicit `t` argument -- without touching
        the original `fn`'s body. Appends `input_name` as a new (size-1)
        input; the `t` argument on the returned system's `fn` is ignored
        (time now arrives through `u`). This is what lets you `connect()` a
        shared clock (see `make_clock`) into this system's time input.
        """
        if input_name in self._input_by_name:
            raise ValueError(f"'{input_name}' is already an input variable of '{self.name}'")
 
        original_fn = self.fn
        m = self.input_size  # size of the *original* input vector, before appending time
 
        def fn(x: jnp.ndarray, u_aug: jnp.ndarray, p: Any, t: Any) -> jnp.ndarray:
            u, t_slot = u_aug[:m], u_aug[m]
            return original_fn(x, u, p, t_slot)
 
        return DynamicalSystem(
            name=self.name,
            state_vars=list(self.state_vars),
            fn=fn,
            input_vars=list(self.input_vars) + [VarSpec(input_name)],
            outputs=list(self.outputs),
            params=self.default_params,
            domain=self.domain,
        )

    # -- parameters shenanigans (Wiggins approved) ---------------------------

    def promote_params(self, param_names: Optional[Sequence[str]] = None,
                                 state_prefix: str = "") -> "DynamicalSystem":
        """
        Turn selected (or, by default, ALL) entries of this system's `params`
        into ordinary STATE variables with trivial dynamics -- dx/dt = 0
        (continuous) or x_next = x (discrete) -- instead of fixed parameters.
        The state-space analogue of `promote_params` (which does the same
        thing but as a wireable input); useful for treating a parameter as
        something to integrate/hold/inspect as state -- e.g. gradient-based
        parameter fitting through a single state vector, or slow parameter
        drift -- rather than something driven externally.
 
        `self.default_params` must be a flat dict of scalar/array leaves (see
        `CompositeSystem.promote_params_to_state` for targeting subsystems
        inside a composite instead). `param_names=None` (default) promotes
        every key; pass an explicit subset for "some". Each promoted
        parameter becomes a new state variable named f"{state_prefix}{name}",
        appended after the existing state (so existing state/output indices
        are unchanged) and sized to match the parameter's own (static)
        shape. The returned system's `default_params` no longer contains the
        promoted keys.
 
        Use `.promoted_initial_state(param_names)` -- called on THIS system,
        BEFORE promoting -- to get the matching initial-state block (the
        parameters' own default values, flattened) to append to your own
        initial condition.
        """
        if not isinstance(self.default_params, dict):
            raise TypeError(
                f"[{self.name}] promote_params requires a flat dict of params, "
                f"got {type(self.default_params).__name__}"
            )
        names = list(self.default_params) if param_names is None else list(param_names)
        unknown = set(names) - set(self.default_params)
        if unknown:
            raise ValueError(f"[{self.name}] unknown parameter name(s): {sorted(unknown)}")
        for n in names:
            if isinstance(self.default_params[n], dict):
                raise TypeError(
                    f"[{self.name}] parameter '{n}' is itself a nested params dict "
                    f"(likely a CompositeSystem's own subsystem params); "
                    f"promote_params only handles flat scalar/array parameter "
                    f"leaves -- target that subsystem directly (e.g. via "
                    f"CompositeSystem.promote_params) instead."
                )
        collide = [n for n in names if n in self._state_by_name]
        if collide:
            raise ValueError(
                f"[{self.name}] parameter name(s) already used as state variable(s): {collide}"
            )
 
        original_fn = self.fn
        n_orig = self.state_size
 
        shapes = {n: np.asarray(self.default_params[n]).shape for n in names}
        sizes = {n: int(np.atleast_1d(np.asarray(self.default_params[n])).size) for n in names}
        new_state_vars = [VarSpec(f"{state_prefix}{n}", sizes[n]) for n in names]
        total_promoted = sum(sizes.values())
        is_discrete = self.domain == "discrete"
 
        remaining_params = {k: v for k, v in self.default_params.items() if k not in names}
 
        def fn(x_aug: jnp.ndarray, u: jnp.ndarray, p: Any, t: Any) -> jnp.ndarray:
            x = x_aug[:n_orig]
            full_p = dict(p)
            offset = n_orig
            promoted_blocks = []
            for n in names:
                size = sizes[n]
                block = x_aug[offset:offset + size]
                promoted_blocks.append(block)
                full_p[n] = block.reshape(shapes[n])
                offset += size
            dx = original_fn(x, u, full_p, t)
            if is_discrete:
                trivial = (jnp.concatenate(promoted_blocks) if promoted_blocks
                           else jnp.zeros((0,), dtype=x_aug.dtype))
            else:
                trivial = jnp.zeros((total_promoted,), dtype=x_aug.dtype)
            return jnp.concatenate([dx, trivial])
 
        return DynamicalSystem(
            name=self.name,
            state_vars=list(self.state_vars) + new_state_vars,
            fn=fn,
            input_vars=self.input_vars,
            outputs=list(self.outputs),
            params=remaining_params,
            domain=self.domain,
        )
    
    # -- composition sugar ---------------------------------------------------

    def __or__(self, other: "DynamicalSystem") -> "CompositeSystem":
        return merge(self, other)

    def __rshift__(self, other: "DynamicalSystem") -> "CompositeSystem":
        return series(self, other)

    def __repr__(self) -> str:
        return (f"{type(self).__name__}(name={self.name!r}, domain={self.domain!r}, "
                f"state_size={self.state_size}, input_size={self.input_size}, "
                f"outputs={list(self.outputs)})")


# --------------------------------------------------------------------------
# Graph construction
# --------------------------------------------------------------------------

def build_graph(subsystems: Sequence[DynamicalSystem], edges: Sequence[Edge]) -> "gt.Graph":
    """
    Build a graph-tool directed graph: one vertex per subsystem, one edge per
    wired connection. `edges` is a list of
        (src_system_name, src_output_var, dst_system_name, dst_input_var)
    tuples. Vertex property 'system_name' and edge property 'mapping'
    (a (src_var, dst_var) tuple) carry the wiring information.
    """
    g = gt.Graph(directed=True)
    name_prop = g.new_vertex_property("object")
    vertex_of = {}
    names_seen = set()
    for s in subsystems:
        if s.name in names_seen:
            raise ValueError(f"duplicate subsystem name '{s.name}'")
        names_seen.add(s.name)
        v = g.add_vertex()
        name_prop[v] = s.name
        vertex_of[s.name] = v
    g.vertex_properties["system_name"] = name_prop

    mapping_prop = g.new_edge_property("object")
    for (src_name, src_var, dst_name, dst_var) in edges:
        if src_name not in vertex_of:
            raise ValueError(f"unknown source system '{src_name}' in edge list")
        if dst_name not in vertex_of:
            raise ValueError(f"unknown destination system '{dst_name}' in edge list")
        e = g.add_edge(vertex_of[src_name], vertex_of[dst_name])
        mapping_prop[e] = (src_var, dst_var)
    g.edge_properties["mapping"] = mapping_prop
    return g


# --------------------------------------------------------------------------
# CompositeSystem
# --------------------------------------------------------------------------

class CompositeSystem(DynamicalSystem):
    """
    A `DynamicalSystem` assembled from other `DynamicalSystem`s according to a
    graph-tool directed graph describing which named outputs feed which named
    inputs. Since it subclasses `DynamicalSystem`, a composite can itself be
    merged/connected into a larger composite (arbitrary nesting).

    You normally build these via `merge(...)` or `connect(...)` below rather
    than calling this constructor directly, but you can do so by having a properly
    built graph with:
    -- "system_name" vertex_property containing the names of the vertices (no need to 
    recursively add the subsystem names).
    -- "mapping" edge_property containing the pair (in_variable, out_variable) of
    each connection between the systems.
    """

    def __init__(self, name: str, subsystems: Sequence[DynamicalSystem], graph: "gt.Graph"):
        self.subsystems = list(subsystems)
        self._sys_by_name = {s.name: s for s in self.subsystems}
        if len(self._sys_by_name) != len(self.subsystems):
            raise ValueError("subsystem names must be unique")
        self.graph = graph

        vprop = graph.vertex_properties["system_name"]
        eprop = graph.edge_properties["mapping"]

        # Canonical ordering is the order of `subsystems`, independent of
        # however graph-tool happens to iterate its own vertices.
        state_offset: Dict[str, int] = {}
        off = 0
        for s in self.subsystems:
            state_offset[s.name] = off
            off += s.state_size
        N = off

        input_offset: Dict[str, int] = {}
        off = 0
        for s in self.subsystems:
            input_offset[s.name] = off
            off += s.input_size
        M = off

        # G[j] = index into concatenate([x_global (len N), u_ext_full (len M)])
        # telling where global input-slot j actually gets its value from.
        # Default: identity (slot j reads from u_ext_full[j], i.e. index N + j).
        G = np.arange(N, N + M, dtype=np.int32)
        covered_dst: set = set()

        for e in graph.edges():
            src_name = vprop[e.source()]
            dst_name = vprop[e.target()]
            src_var, dst_var = eprop[e]
            src_sys = self._sys_by_name[src_name]
            dst_sys = self._sys_by_name[dst_name]

            if not src_sys.has_output_var(src_var):
                raise ValueError(f"'{src_var}' is not a declared output of system '{src_name}'")
            if not dst_sys.has_input(dst_var):
                raise ValueError(f"'{dst_var}' is not a declared input of system '{dst_name}'")

            s0, s1 = src_sys.state_slice(src_var)
            d0, d1 = dst_sys.input_slice(dst_var)
            if (s1 - s0) != (d1 - d0):
                raise ValueError(
                    f"size mismatch wiring {src_name}.{src_var} (size {s1 - s0}) -> "
                    f"{dst_name}.{dst_var} (size {d1 - d0})"
                )

            global_src = np.arange(state_offset[src_name] + s0, state_offset[src_name] + s1)
            global_dst = np.arange(input_offset[dst_name] + d0, input_offset[dst_name] + d1)

            for gd in global_dst.tolist():
                if gd in covered_dst:
                    raise ValueError(
                        f"input '{dst_var}' of system '{dst_name}' is wired more than once"
                    )
                covered_dst.add(gd)
            G[global_dst] = global_src

        # Which global input slots remain free (unconnected) -> these become
        # this composite's own exposed input_vars, in subsystem/var order.
        free_ranges: List[Tuple[int, int]] = []
        input_vars: List[VarSpec] = []
        for s in self.subsystems:
            for v in s.input_vars:
                lo, hi = s.input_slice(v.name)
                slot0 = input_offset[s.name] + lo
                if slot0 not in covered_dst:
                    free_ranges.append((slot0, slot0 + v.size))
                    input_vars.append(VarSpec(f"{s.name}.{v.name}", v.size))

        free_slot_indices = (
            np.concatenate([np.arange(a, b) for a, b in free_ranges])
            if free_ranges else np.zeros((0,), dtype=np.int32)
        )

        state_vars = [
            VarSpec(f"{s.name}.{v.name}", v.size) for s in self.subsystems for v in s.state_vars
        ]
        outputs = [f"{s.name}.{o}" for s in self.subsystems for o in s.outputs]

        domains = {s.domain for s in self.subsystems}
        domain: Domain = domains.pop() if len(domains) == 1 else "hybrid"
        if domain == "hybrid":
            warnings.warn(
                f"CompositeSystem '{name}' mixes continuous and discrete subsystems "
                f"(domain='hybrid'). This framework only assembles the dynamics "
                f"function; you are responsible for integrating each part correctly."
            )

        default_params = {s.name: s.default_params for s in self.subsystems}

        # Stash precomputed, static (numpy/jax) layout info before calling
        # super().__init__, which will invoke self._composite_fn via self.fn.
        self._N, self._M = N, M
        self._state_offset = state_offset
        self._input_offset = input_offset
        self._G = jnp.asarray(G)
        self._free_slot_indices = jnp.asarray(free_slot_indices, dtype=jnp.int32)

        super().__init__(
            name=name,
            state_vars=state_vars,
            input_vars=input_vars,
            outputs=outputs,
            params=default_params,
            domain=domain,
            fn=self._composite_fn,
        )

    def _composite_fn(self, x_global: jnp.ndarray, u_free: jnp.ndarray,
                       params: Dict[str, Any], t: Any) -> jnp.ndarray:
        # Set variables to 0 and to u_free
        u_ext_full = jnp.zeros((self._M,), dtype=x_global.dtype).at[self._free_slot_indices].set(u_free)
        augmented = jnp.concatenate([x_global, u_ext_full])
        eff_u = augmented[self._G]

        dxs = []
        # This is the meat: 
        # The indexes, both of the state and of the inputs, are necessary to properly pass the variables to the single subsystems
        for s in self.subsystems:
            x0 = self._state_offset[s.name]
            x1 = x0 + s.state_size
            u0 = self._input_offset[s.name]
            u1 = u0 + s.input_size
            xi = x_global[x0:x1]
            ui = eff_u[u0:u1]
            pi = params.get(s.name, None) # TODO: could be obscure: will use default parameters for all unspecified subsystems 
            dxs.append(s(xi, ui, pi, t)) # this uses the __call__ of the subsystem; should it use s.fn instead? I think not
        return jnp.concatenate(dxs) if dxs else jnp.zeros((0,), dtype=x_global.dtype)

    def flatten_params(self, params: Optional[Any] = None, _prefix: str = "") -> Dict[str, Any]:
        """
        Collapse the nesting `_composite_fn` needs -- one dict level per
        composed CompositeSystem -- into a single dict keyed by dotted
        subsystem path, e.g. {"outer.inner.leaf1": {...}, "outer.leaf3": {...}}.
        Only the composition-induced nesting is removed; each *leaf*
        subsystem's own parameter pytree is kept as-is (not flattened
        further). `params` defaults to `self.default_params`.
        """
        if params is None:
            params = self.default_params
        flat: Dict[str, Any] = {}
        for s in self.subsystems:
            key = f"{_prefix}{s.name}"
            sub_params = params[s.name]
            if isinstance(s, CompositeSystem):
                flat.update(s.flatten_params(sub_params, _prefix=f"{key}."))
            else:
                flat[key] = sub_params
        return flat

    def unflatten_params(self, flat: Dict[str, Any], _prefix: str = "",
                          _missing: Optional[List[str]] = None) -> Any:
        """Inverse of `flatten_params`: rebuild the nested dict that `self.fn`
        (i.e. `_composite_fn`) actually expects as its `params` argument.
        If `flat` is missing any leaf subsystem's key, raises a single
        KeyError listing *all* of them (not just the first one found)."""
        top_level = _missing is None
        if top_level:
            _missing = []
 
        nested: Dict[str, Any] = {}
        for s in self.subsystems:
            key = f"{_prefix}{s.name}"
            if isinstance(s, CompositeSystem):
                nested[s.name] = s.unflatten_params(flat, _prefix=f"{key}.", _missing=_missing)
            elif key in flat:
                nested[s.name] = flat[key]
            else:
                _missing.append(key)
                nested[s.name] = None  # placeholder; discarded below via the raise
 
        if top_level and _missing:
            raise KeyError(f"missing flat param key(s): {sorted(_missing)}")
        return nested

    # convenience: pull a named subsystem's own slice back out of the
    # composite's global state/output, e.g. for plotting/inspection.
    def subsystem_state(self, x_global: jnp.ndarray, sys_name: str) -> jnp.ndarray:
        s = self._sys_by_name[sys_name]
        a = self._state_offset[sys_name]
        return x_global[a:a + s.state_size]

    def autonomize(
        self,
        submodules: Optional[Sequence[str]] = None,
        clock: Optional[DynamicalSystem] = None,
        clock_output: Optional[str] = None,
        input_name: str = "t_in",
        name: Optional[str] = None,
    ) -> "CompositeSystem":
        """
        CompositeSystem-specific override of `DynamicalSystem.autonomize`.
 
        Recursively wires a shared `clock` into the named `submodules`,
        wherever they live inside this composite -- at any nesting depth.
        Each matched node is adapted via the base (leaf-level)
        `DynamicalSystem.autonomize(input_name)`, exactly as you'd do by
        hand for one system; a matched name that is itself a nested
        CompositeSystem is adapted as a whole, so the entire subtree beneath
        it ends up sharing that one substituted time.
 
        Unlike the generic `DynamicalSystem.autonomize` (which flattens
        everything down into one opaque `fn`), this always goes back through
        `connect()`, so the result is a genuine `CompositeSystem` -- `.graph`
        and `.subsystems` stay intact. This replaces the old standalone
        `connect_clock(...)` function; call it as `composite.autonomize(...)`.
 
        submodules : names of the subsystems to clock, at any nesting depth.
                     None (default) means every *immediate* child of this
                     composite.
        clock      : a DynamicalSystem exposing time as its output, e.g.
                     built with `make_clock(...)`. Required.
        """
        if clock is None:
            raise ValueError(
                "CompositeSystem.autonomize(...) requires a `clock` system "
                "(e.g. built with make_clock(...))"
            )
 
        top_children, top_edges = _unpack(self)
        base_name = name or self.name
 
        target_names = set(submodules) if submodules is not None else {c.name for c in top_children}
 
        if clock_output is None:
            if len(clock.outputs) != 1:
                raise ValueError(
                    f"clock '{clock.name}' has {len(clock.outputs)} outputs; "
                    f"pass clock_output explicitly to disambiguate"
                )
            clock_output = clock.outputs[0]
 
        new_top_children, new_edges, matched = [], list(top_edges), set()
        for child in top_children:
            new_child, bubbled, child_matched = _wire_clock_recursive(child, target_names, input_name)
            matched |= child_matched
            for local_name in bubbled:
                new_edges.append((clock.name, clock_output, new_child.name, local_name))
            new_top_children.append(new_child)
 
        missing = target_names - matched
        if missing:
            raise ValueError(f"submodule(s) not found (recursively): {sorted(missing)}")
 
        return connect([clock] + new_top_children, new_edges, name=base_name)

    def promote_params(
        self,
        targets: Union[Sequence[str], Dict[str, Optional[Sequence[str]]]],
        state_prefix: str = "",
        name: Optional[str] = None,
    ) -> "CompositeSystem":
        """
        CompositeSystem-specific override of
        `DynamicalSystem.promote_params`: recursively promote
        parameters of NAMED subsystems -- at any nesting depth -- into
        ordinary state variables with trivial dynamics (dx/dt = 0, or
        x_next = x for discrete subsystems), while still returning a genuine
        CompositeSystem (`.graph`/`.subsystems` preserved, since this goes
        back through `connect()` at the end).
 
        targets : either
          - a plain sequence of subsystem names -> promote ALL of each named
            subsystem's own parameters, or
          - a dict {subsystem_name: param_names_or_None} -> promote just the
            given parameter names for that subsystem (None means "all",
            same as the base method's default).
 
        Each matched subsystem is adapted via the base, leaf-level
        `DynamicalSystem.promote_params(...)` (called explicitly on
        the base class, bypassing this override -- same reasoning as the
        sibling `promote_params`/`autonomize` overrides). The newly-promoted
        state is appended after each subsystem's existing state, so existing
        state/output indices elsewhere are unaffected; get matching initial
        values via `.promoted_initial_state(...)` on the ORIGINAL subsystem.
        """
        target_map: Dict[str, Optional[Sequence[str]]] = (
            dict(targets) if isinstance(targets, dict) else {t: None for t in targets}
        )
 
        top_children, top_edges = _unpack(self)
        base_name = name or self.name
 
        new_top_children: List[DynamicalSystem] = []
        matched: set = set()
        for child in top_children:
            new_child, child_matched = _promote_params_recursive(child, target_map, state_prefix)
            matched |= child_matched
            new_top_children.append(new_child)
 
        missing = set(target_map) - matched
        if missing:
            raise ValueError(f"subsystem(s) not found (recursively): {sorted(missing)}")
 
        return connect(new_top_children, top_edges, name=base_name)


# --------------------------------------------------------------------------
# Public composition constructors
# --------------------------------------------------------------------------

def connect(subsystems: Sequence[DynamicalSystem], edges: Sequence[Edge],
            name: str = "composite") -> CompositeSystem:
    """
    Wire `subsystems` together according to `edges`, a list of
        (src_system_name, src_output_var, dst_system_name, dst_input_var)
    tuples, and return one CompositeSystem. `edges` may describe any directed
    graph topology, including cycles (feedback loops) -- see module docstring
    for why cycles are safe here.
    """
    g = build_graph(subsystems, edges)
    return CompositeSystem(name, subsystems, g)


def merge(*subsystems: DynamicalSystem, name: str = "merged") -> CompositeSystem:
    """
    Block-diagonal composition: concatenate every state/input/param, with NO
    coupling between subsystems -- each keeps evolving under its own,
    independent dynamics function. Equivalent to `connect(subsystems, [])`.
    """
    g = build_graph(subsystems, edges=[])
    return CompositeSystem(name, subsystems, g)


def series(a: DynamicalSystem, b: DynamicalSystem, name: Optional[str] = None) -> CompositeSystem:
    """
    Convenience cascade: auto-wire every output of `a` to the identically
    *named* (and same-sized) input of `b`. For fan-out, feedback, or more
    than two systems, use `connect(...)` directly with an explicit edge list.
    """
    edges: List[Edge] = []
    for o in a.outputs:
        if b.has_input(o):
            a_size = a._state_by_name[o].size
            b_size = b._input_by_name[o].size
            if a_size == b_size:
                edges.append((a.name, o, b.name, o))
    if not edges:
        raise ValueError(
            f"series(): no matching same-name/same-size output(of '{a.name}') -> "
            f"input(of '{b.name}') pairs found; use connect(...) explicitly."
        )
    return connect([a, b], edges, name=name or f"{a.name}_then_{b.name}")


def make_clock(name: str = "clock", rate: float = 1.0, domain: Domain = "continuous") -> DynamicalSystem:
    """
    A trivial autonomous system whose sole state variable *is* time itself:
        continuous:  d(tau)/dt = rate           (rate=1 recovers ordinary time)
        discrete:    tau_next  = tau + rate      (rate=1 recovers the step index)
    Its output is that same state, so -- unlike the special-cased `t` argument
    on ordinary systems -- it's an ordinary wireable output and can be fanned
    out via `connect()` to any number of other subsystems that read time
    through a normal *input* variable instead of through the `t` argument.
    Useful when several composed subsystems should share one common clock.
    """
    is_continuous = domain == "continuous"
 
    def fn(x, u, p, t):
        if is_continuous:
            return jnp.ones((1,), dtype=x.dtype) * p["rate"]
        return x + p["rate"]
 
    return DynamicalSystem(
        name=name,
        state_vars=[VarSpec("tau")],
        outputs=["tau"],
        params={"rate": rate},
        domain=domain,
        fn=fn,
    ) 
